### ISSUE TITLE
Possible precedence issue with control flow operator at /usr/share/suncron/lib/CalcTime.pm line 175.

### ISSUE THREAD

**Issue by K-Ko** [6feet5/suncron#2]
Line https://github.com/6feet5/suncron/blob/master/src/lib/CalcTime.pm#L175 have to be changed from

```
return ($self->{_sunset}->hours != $self->{_sunrise}->hours) and ($self->{_sunset}->minutes != $self->{_sunrise}->minutes);
```

to

```
return (($self->{_sunset}->hours != $self->{_sunrise}->hours) and ($self->{_sunset}->minutes != $self->{_sunrise}->minutes));
```

(And one more bracket)

**Comment by awitherow** [comment]
@6feet5 just want to verify that this issue and https://github.com/6feet5/suncron/issues/1 are closed?

**Comment by 6feet5** [comment]
@awitherow Pull-request has been merged but I'm a total newbie when it comes to GitHub. Looks like I forgot a step in the workflow. I need to read up a bit on how to work with GitHub :)

**Comment by awitherow** [comment]
@6feet5 no worries at all! Just wanted to say something and see if you were still bumping around on Github :)

**Comment by 6feet5** [comment]
@awitherow I'm still bumping :)
The progress on this project is kind of slow. It was an attempt by me to learn some pearl when someone wanted me to share it, and so I did without thinking about how... GitHub it was.
 Still, I need to read up a bit on how the workflow goes. Thanks for paying attention :)

**Comment by awitherow** [comment]
Would love to help you with that.

I am interested in using this to create something for myself. I will submit an issue with my ideas and maybe it can be used as a basis to expand documentation and have some cool examples!
